<template>
    <div class="loadingio-spinner-heart-2h5wlb9e2bc"><div class="ldio-eq0msao7mc6">
    <div><div></div></div>
    </div></div>
</template>

<script>
export default {

}
</script>

<style>
@keyframes ldio-eq0msao7mc6 {
0% { transform: scale(.85) }
5% { transform: scale(1) }
39% { transform: scale(.75) }
45% { transform: scale(.9) }
60% { transform: scale(.85) }
100% { transform: scale(.8) }
}
.ldio-eq0msao7mc6 > div {
  animation: ldio-eq0msao7mc6 1s infinite cubic-bezier(0.215, 0.61, 0.355, 1);
  transform-origin: 100px 100px;
}
.ldio-eq0msao7mc6 > div div {
  top: 350px;
  left: 60px;
  position: absolute;
  width: 80px;
  height: 80px;
  background: #e90c59;
  transform: rotate(45deg);
}
.ldio-eq0msao7mc6 > div div:after, .ldio-eq0msao7mc6 > div div:before {
  content: " ";
  position: absolute;
  display: block;
  width: 80px;
  height: 80px;
  background: #e90c59;
}
.ldio-eq0msao7mc6 > div div:before {
  left: -52px;
  border-radius: 50% 0 0 50%;
}
.ldio-eq0msao7mc6 > div div:after {
  top: -52px;
  border-radius: 50% 50% 0 0;
} 
.loadingio-spinner-heart-2h5wlb9e2bc {
  width: 200px;
  height: 500px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-eq0msao7mc6 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-eq0msao7mc6 div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>